[package]
name = "image-filters-block"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "./server/lib.rs"

[dependencies]
photon-rs = "0.3.1"
wasm-bindgen = "0.2.78"

[dependencies.web-sys]
version = "0.3.56"
features = ["console"]
