name: Build production zip file
on: push
jobs:
    build:
        name: Build zip file
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release --all-features
            - name: npm install and build
              run: |
                  npm ci
                  npm run build
              env:
                  CI: true

            - name: Package
              uses: actions/upload-artifact@v3
              with:
                  name: image-filters
                  retention-days: 5
                  path: |
                      ${{ github.workspace }}/
                      !${{ github.workspace }}/node_modules/
                      !${{ github.workspace }}/scripts/
                      !${{ github.workspace }}/target/
                      !${{ github.workspace }}/.git/
                      !${{ github.workspace }}/.github/
                      !${{ github.workspace }}/.wordpress-org/
                      !${{ github.workspace }}/assets/
                      !${{ github.workspace }}/package-lock.json
